# Generated by Django 5.2.4 on 2025-07-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_sale_amount_paid_sale_balance_sale_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
    ]
