# Generated by Django 5.2.4 on 2025-07-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_invoice_remove_sale_amount_paid_remove_sale_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='job_type',
        ),
    ]
