# Generated by Django 5.2.4 on 2025-08-03 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Organization name (e.g., 'ABC Company')", max_length=100, unique=True)),
                ('subdomain', models.CharField(help_text="Subdomain for tenant (e.g., 'abc' for abc.yourapp.com)", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase letters, numbers, and hyphens only', regex='^[a-z0-9]([a-z0-9\\-]{0,61}[a-z0-9])?$')])),
                ('database_name', models.CharField(help_text='Database name for this tenant', max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_email', models.EmailField(help_text='Primary admin email for this organization', max_length=254)),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Maximum number of users allowed for this tenant')),
                ('supports_multi_location', models.BooleanField(default=True, help_text='Whether this tenant uses multiple locations')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g., 'Downtown Store', 'Warehouse A')", max_length=100)),
                ('code', models.CharField(help_text="Short code for location (e.g., 'DT', 'WH1')", max_length=10)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
                'unique_together': {('tenant', 'code'), ('tenant', 'name')},
            },
        ),
    ]
