# Generated by Django 5.2.4 on 2025-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='database_engine',
            field=models.CharField(default='django.db.backends.postgresql', help_text='Database engine (e.g., django.db.backends.sqlite3)', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_host',
            field=models.CharField(blank=True, default='', help_text='Database host (leave empty to use default)', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_password',
            field=models.CharField(blank=True, default='', help_text='Database password (leave empty to use default)', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_port',
            field=models.PositiveIntegerField(blank=True, help_text='Database port (leave empty to use default)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_url',
            field=models.URLField(blank=True, help_text='Complete database URL (overrides other settings if provided)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_user',
            field=models.CharField(blank=True, default='', help_text='Database username (leave empty to use default)', max_length=100),
        ),
    ]
